preserve_hierarchy: true
files:
  - source: upload/admin/language/en-gb/*.php
    translation: upload/admin/language/%locale%/%file_name%.%file_extension%
  - source: upload/admin/language/en-gb/**/*.php
    translation: upload/admin/language/%locale%/**/%file_name%.%file_extension%
  - source: upload/catalog/language/en-gb/*.php
    translation: upload/catalog/language/%locale%/%file_name%.%file_extension%
  - source: upload/catalog/language/en-gb/**/*.php
    translation: upload/catalog/language/%locale%/**/%file_name%.%file_extension%
  - source: upload/install/language/en-gb/*.php
    translation: upload/install/language/%locale%/%file_name%.%file_extension%
  - source: upload/install/language/en-gb/**/*.php
    translation: upload/install/language/%locale%/**/%file_name%.%file_extension%
  - source: upload/extension/opencart/admin/language/en-gb/**/*.php
    translation: upload/extension/opencart/admin/language/%locale%/**/%file_name%.%file_extension%
  - source: upload/extension/opencart/catalog/language/en-gb/**/*.php
    translation: upload/extension/opencart/catalog/language/%locale%/**/%file_name%.%file_extension%
